export const GET_COUNTRIES = "GET_COUNTRIES";
export const PAGINATE = "PAGINATE";
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
export const GET_DETAIL = "GET_DETAIL";
export const ORDER = "ORDER";
export const ORDER_POPULATION = "ORDER_POPULATION";
export const FILTER_CONTINENTS = "FILTER_CONTINENTS";
export const FILTER_ACTIVITY = "FILTER_ACTIVITY";